### ISSUE TITLE
springboot start pulsar error

### ISSUE THREAD

**Issue by chrismayday** [majusko/pulsar-java-spring-boot-starter#185]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Caused by: java.lang.NoClassDefFoundError: reactor/core/publisher/Sinks
	at io.github.majusko.pulsar.consumer.ConsumerAggregator.<init>(ConsumerAggregator.java:34) ~[pulsar-java-spring-boot-starter-1.0.7.jar:1.0.7]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	... 20 more
Caused by: java.lang.ClassNotFoundException: reactor.core.publisher.Sinks
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
	at io.github.majusko.pulsar.consumer.ConsumerAggregator.<init>(ConsumerAggregator.java:34) ~[pulsar-java-spring-boot-starter-1.0.7.jar:1.0.7]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490) ~[?:?]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:204) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:310) ~[spring-beans-5.2.15.RELEASE.jar:5.2.15.RELEASE]
	... 20 more

**Expected behaviour**

**Additional context**

**Comment by majusko** [comment]
Hey @chrismayday, have you resolved the issue?

**Comment by lzc-up** [comment]
hey, Has this issue bug resolved? I also have this question

**Comment by Mark916** [comment]
This bug is still here , is there any resolved method?
